const subCategories = {
  lehenga: [
    "Printed Lehenga",
    "Embroidered Lehenga",
    "Sequinned Lehenga",
    "Mirror Work Lehenga",
    "Zardosi Lehenga",
    "Handwoven Lehenga",
    "Layered Lehenga",
    "Panelled Lehenga",
    "Ruffled Lehenga",
    "Silk Lehenga",
    "Velvet Lehenga",
    "Net Lehenga",
    "Organza Lehenga",
    "Georgette Lehenga",
    "Bridal Lehenga",
    "Festive Lehenga",
    "Indo-Western Lehenga",
  ],

  saree: [
    "Printed Saree",
    "Embroidered Saree",
    "Handwoven Saree",
    "Sequinned Saree",
    "Zari Saree",
    "Silk Saree",
    "Organza Saree",
    "Georgette Saree",
    "Chiffon Saree",
    "Cotton Saree",
    "Tissue Saree",
    "Banarasi Saree",
    "Kanjivaram Saree",
    "Bandhani Saree",
    "Chikankari Saree",
    "Ruffle Saree",
    "Pre-draped Saree",
    "Fusion Saree",
  ],

  blouse: [
    "Embroidered Blouse",
    "Printed Blouse",
    "Sequinned Blouse",
    "Mirror Work Blouse",
    "Zardosi Blouse",
    "Cape Blouse",
    "Ruffle Blouse",
    "Halter Neck Blouse",
    "High Neck Blouse",
    "Padded Blouse",
    "Backless Blouse",
    "Peplum Blouse",
    "Crop Blouse",
  ],

  gown: [
    "Embroidered Gown",
    "Printed Gown",
    "Layered Gown",
    "Draped Gown",
    "Sequinned Gown",
    "Ball Gown",
    "Fusion Gown",
    "Evening Gown",
    "Cocktail Gown",
    "Metallic Gown",
    "Ruffled Gown",
    "Cape Gown",
    "Pleated Gown",
  ],

  anarkalis: [
    "Printed Anarkali",
    "Embroidered Anarkali",
    "Layered Anarkali",
    "Floor-Length Anarkali",
    "Short Anarkali",
    "Jacket Anarkali",
    "Silk Anarkali",
    "Chanderi Anarkali",
    "Cotton Anarkali",
    "Festive Anarkali",
    "Bridal Anarkali",
  ],

  shararas: [
    "Printed Sharara Set",
    "Embroidered Sharara Set",
    "Mirror Work Sharara Set",
    "Sequinned Sharara Set",
    "Layered Sharara Set",
    "Jacket Sharara Set",
    "Silk Sharara Set",
    "Georgette Sharara Set",
    "Cotton Sharara Set",
    "Festive Sharara Set",
  ],

  "kurta-sets": [
    "Printed Kurta Set",
    "Embroidered Kurta Set",
    "Anarkali Kurta Set",
    "Straight Cut Kurta Set",
    "A-line Kurta Set",
    "Cape Kurta Set",
    "Layered Kurta Set",
    "Festive Kurta Set",
    "Office Wear Kurta Set",
    "Casual Kurta Set",
    "Indo-Western Kurta Set",
  ],

  kaftans: [
    "Printed Kaftan",
    "Embroidered Kaftan",
    "Belted Kaftan",
    "Cape Kaftan",
    "Layered Kaftan",
    "Maxi Kaftan",
    "Short Kaftan",
    "Festive Kaftan",
    "Beach Kaftan",
  ],
};

export default subCategories;
